version: '3.5'
services:
  tomcat8:
    image: joordonezoarago/sap-neo-tomcat8:dev
    ports:
     - "8080:8080"
     - "8443:8443"
    volumes:
     - ./target:/tomcat/webapps
     - .cfg/conf:/tomcat
     - .cfg/config_master:/tomcat